model = "SGP4"

bbox = [30.8251, -21.2695, 66.0699, 48.457561]
interval = 5
animation = false
hosts = ["192.168.0.6:1969", "192.168.0.7:1969", "192.168.0.8:1969", "192.168.0.9:1969"]
peeringhosts = ["192.168.0.6:1970", "192.168.0.7:1970", "192.168.0.8:1970", "192.168.0.9:1970"]
dbhost = "192.168.0.2:8000"
database = true

[networkparams]
islpropagation = 3.336e-6
bandwidth = 10_000
mincommsaltitude = 100_000
minelevation = 40
gstpropagation = 3.336e-6
groundstationconnectiontype = "shortest"

[computeparams]
vcpu_count = 1
mem_size_mib = 1024
ht_enabled = false
bootparams = ""
kernel = "vmlinux.bin"
rootfs = "server.img"
disk_size_mib =  20_000

[[shell]]
planes = 34
sats = 34
altitude = 630
inclination = 51.9
arcofascendingnodes = 360.0
eccentricity = 0.0